#pragma once
#include <Arduino.h>

// Generic engine for any animated pixel-art sprite generated by
// bin_to_header.py. One SpriteAnim instance = one animation running
// on screen; make as many as you want, each pointing at different data.
struct SpriteAnim {
  const uint16_t* data;        // pass the array from your generated header,
                                // e.g. (const uint16_t*)deerData
  uint8_t width, height;       // e.g. DEER_W, DEER_H
  uint8_t frameCount;          // e.g. DEER_FRAMES
  uint16_t transparentKey;     // e.g. DEER_TRANSPARENT_KEY
  unsigned long frameIntervalMs;

  // runtime state - leave these at 0, spriteBegin() sets them up
  int x = 0, y = 0, scale = 1;
  uint8_t currentFrame = 0;
  unsigned long lastFrameTime = 0;
};

// Call once from setup(). x,y = top-left corner on screen.
// scale = size of each source pixel in screen pixels.
void spriteBegin(SpriteAnim &anim, int x, int y, int scale);

// Call every loop(). Advances on its own internal timer.
void spriteUpdate(SpriteAnim &anim);
