#!/usr/bin/env python3
"""
Convert one or more raw RGB565 .bin files into a C header usable in Arduino.

Usage (single image):
    python3 bin_to_header.py frame0.bin --width 20 --height 20 --name deer --out DeerSprite.h

Usage (multiple frames -> one array of frames, for animation):
    python3 bin_to_header.py frame0.bin frame1.bin frame2.bin --width 20 --height 20 --name deer --out DeerSprite.h

Assumes little-endian byte order (2 bytes per pixel, low byte first) --
matches what most RGB565 export tools produce. If colors come out wrong
(e.g. looking like a totally different hue than expected), the file was
probably big-endian instead -- pass --big-endian to flip it.
"""

import argparse
import os
import sys


def read_pixels(path, width, height, big_endian):
    # RGB565 packs all colours in 16 bits, so we *2 to get the necessary bytes
    expected_bytes = width * height * 2
    # rb = read binary
    with open(path, "rb") as f:
        data = f.read()

    if len(data) != expected_bytes:
        print(
            f"WARNING: {path} is {len(data)} bytes, expected {expected_bytes} "
            f"for a {width}x{height} RGB565 image. Check your width/height.",
            # outputs it to error stream
            file=sys.stderr,
        )

    pixels = []
    for i in range(0, len(data) - 1, 2):
        b0, b1 = data[i], data[i + 1]
        # depending on if it's big or small endian it:
            # shifts the 8 right bits to occupy the upper half of the 16 bit value
            # then combines it with the other lowe half of the other value
        val = (b0 << 8) | b1 if big_endian else (b1 << 8) | b0
        pixels.append(val)
    return pixels


def main():
    ap = argparse.ArgumentParser(prog="bin_to_header",
        # __doc__ is just the starter string at the top of the file
        description=__doc__,
        # RawDescriptionHelpFormatter tells the ap that the description is 
        # already formatted correctly and should not be formated differently
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        # name of the arg
        "inputs",
        # '+' all command-line arguments present are gathered into a list.
        # Additionally, an error message will be generated if there wasn’t at 
        # least one command-line argument present.
        nargs="+",
        help="one or more .bin files (multiple = animation frames, in order)")
    ap.add_argument(
        "-w",
        "--width",
        type=int, 
        required=True)
    ap.add_argument(
        "-ht",
        "--height",
        type=int,
        required=True)
    ap.add_argument(
        "-n",
        "--name",
        required=True,
        help="base name for the array/defines, e.g. 'deer'")
    ap.add_argument("-o",
        "--out",
        required=True,
        help="output .h file path")
    ap.add_argument(
        "-b",
        "--big-endian",
        # just saves a value, big-endian=True
        action="store_true",
        help="use if colors look wrong with default little-endian")
    ap.add_argument(
        "-tk",
        "--transparent-key",
        default="0x0000",
        help="pixel value treated as transparent\
        when drawing (default 0x0000 = black)")
    args = ap.parse_args()

    w, h, name = args.width, args.height, args.name
    # if there are multiple files to parse there are multiple inputs ( which is an arg )
    frames = [read_pixels(p, w, h, args.big_endian) for p in args.inputs]
    n_frames = len(frames)
    guard = f"{name.upper()}_SPRITE_H"

    lines = []
    lines.append(f"#pragma once")
    lines.append(f"#include <Arduino.h>")
    lines.append("")
    lines.append(f"// Auto-generated by bin_to_header.py from: {', '.join(os.path.basename(p) for p in args.inputs)}")
    lines.append(f"#define {name.upper()}_W {w}")
    lines.append(f"#define {name.upper()}_H {h}")
    lines.append(f"#define {name.upper()}_FRAMES {n_frames}")
    lines.append(f"#define {name.upper()}_TRANSPARENT_KEY {args.transparent_key}")
    lines.append("")

    if n_frames == 1:
        # creates a new matrix of unit16_t values called {name}Data of size 
        # {name.upper()}_W * {name.upper()}
        # with the codeword PROGMEM which saves the data to flash memory rather than RAM
        # then creates rows, {{}, {}, {}} in this case just {{}};
        lines.append(
            f"static const uint16_t {name}Data[{name.upper()}_W * {name.upper()}_H]"
            f" PROGMEM = {{")
        for row in range(h):
            # slices out one row of pixels
            # (a chunk of w values) from the flat pixel list,
            # using row-major order.
                # it's a 1D array, so [NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN]
                # this way we get all values skipping w amount each time untill 
                # we reach ( row + 1 ) * w which will allow us to get the last chunk
            row_vals = frames[0][row * w:(row + 1) * w]
            # result will be [  0x1A2B, ..., [num],]
            # it is fine that we leave a comma 
            # and the first comma doesn't get added apparently
            lines.append("  " + ", ".join(f"0x{v:04X}" for v in row_vals) + ",")
        lines.append("};")
    else:
        # creates the variable 
            # static const uint16_t {name}Data[{name.upper()}_FRAMES] which is n_frames
            # with size of each cell [{name.upper()}_W * {name.upper()}_H]
        lines.append(
            f"static const uint16_t {name}Data[{name.upper()}_FRAMES]"
            f"[{name.upper()}_W * {name.upper()}_H] PROGMEM = {{"
        )
        # same as before but I think it just adds a number for each frame
        # static const uint16_t deerData[DEER_FRAMES][DEER_W * DEER_H] PROGMEM = {
        # {   // frame 0 0x1A2B, 0x3C4D, 0x5E6F, 0x7890,},
        for fi, frame in enumerate(frames):
            lines.append(f"  {{ // frame {fi}")
            for row in range(h):
                row_vals = frame[row * w:(row + 1) * w]
                lines.append("    " + ", ".join(f"0x{v:04X}" for v in row_vals) + ",")
            lines.append("  },")
        lines.append("};")

    lines.append("")

    # joins all lines with a newline at the end of them
    with open(args.out, "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {args.out}: {n_frames} frame(s), {w}x{h} each")


if __name__ == "__main__":
    main()